config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'student/new'
  post 'student/create'
  patch 'student/update'
  #get 'student/list'
  get 'student/show'
  get 'student/edit'
  get 'student/delete'
  get 'student/update'
  post 'dashboard/search_professor'
  post 'dashboard/search_course'
  get 'dashboard/show_professor'
  get 'dashboard/show_course'

  get 'school/list'
  get 'school/show'

  get 'department/show'

  get 'professor/show'

  get 'course/show'

  get 'review_course/new'
  patch 'review_course/create'

  get 'review_professor/new'
  patch 'review_professor/create'
  
  # Refer to final site URLs
  get '/', to: 'dashboard#index'
  get '/sign-up', to: 'student#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/map', to: 'map#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/views/home/list.html.erb
<% if @students.blank? %>
<p>There are not any students currently in the system.</p>
<% else %>
<p>These are the current students in our system</p>
<p><%= link_to "Sign-up", sign_up_path%></p>

<ul id = "Students">
   <% @students.each do |c| %>
   <li>
        <%= link_to c.user_id, {:action => 'show', :id => c.user_id} -%>
        <b> <%= link_to 'Edit', {:action => 'edit', :id => c.user_id} %></b>
        <b> <%= link_to "Delete", {:action => 'delete', :id => c.user_id},
            data: { confirm: 'Are you sure?' } %></b>
   </li>
</ul>

<% end %>
<p><%= link_to "Add new Student", {:action => 'new' }%></p>
<% end %>